const userActionTypes = {
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  SET_USER: 'SET_USER',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',
};

export default userActionTypes;